export default {
  OK: '확인',
  CANCEL: '취소',
  SMART_EYE: 'E',
  SMART_PLUG: 'P',
  EMAIL_ERR: '이메일 형식이 아닙니다.',
  SHORT_PWD: '비밀번호가 짧습니다.',
  NOTEQUAL_PWD: '비밀번호가 맞지않습니다.',
  PHONE_ERR: '연락처를 입력해주세요.',
  AREA_ERR: '지역을 선택해주세요.',
  TERMS_ERR: '약관에 동의해주세요.',
  EMPTY_EMAIL: '이메일을 입력해주세요.',
  EMPTY_PWD: '비밀번호를 입력해주세요.',
  EMPTY_NAME: '이름을 입력해주세요.',
  EMPTY_NUMBER: '인증번호를 입력해주세요.',
  FIND_UUIS: '기기와 연결을 진행해주세요.',
  CONN_WIFI: '사용중인 무선 공유기를 연결해주세요.',
  REG_COMP: '기기등록을 완료하였습니다.',
};
